# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb01c3c6ad87d34d5cc7a5710530f3c1e7b49299e4d1eb36d65759177b74036cd8a98ed74bf12f7d2f99f1a99d0b80460bcd63ca951a940b7a3b43fe4a5c0d7

test:
  secret_key_base: 1e20f9b9631f3b36e3eaaaa5e2daafdc86c07c02d72374c962f3629668df14744b96d867c65e2409371fc59ba2dd16d6d6aadcb7730927dfca20bcb857557658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
